### ISSUE TITLE
Underscores inserted in aggregation field names

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/hazimp#61]
When using the aggregation function to produce a table, the column names are split with underscores

Ccnfiguration:

```
 - aggregation:
     groupby: POSTCODE
     kwargs:
      structural: [mean, max, std]
      structural_loss: [mean, sum]
      REPLACEMENT_VALUE: [mean, sum]
      CONTENTS_VALUE: [mean]
```

Output:
```
(_'_P_O_S_T_C_O_D_E_'_,_   _'_'_)
(_'_s_t_r_u_c_t_u_r_a_l_'_,_ _'_m_e_a_n_'_)
(_'_s_t_r_u_c_t_u_r_a_l_'_,_ _'_m_a_x_'_)
(_'_s_t_r_u_c_t_u_r_a_l_'_,_ _'_s_t_d_'_)

```
